### ISSUE TITLE
Beds Explode in the Overworld

### ISSUE THREAD

**Issue by psychofad** [lumien231/Perfect-Spawn#1]
I used the example config and changed the dimension to 0, set up the X, Y, and Z coords and left the options set to true on the optional things and when I place a bed down in the overworld it explodes!

Please FIX this!

**Comment by 4rz0** [comment]
Has this been fixed?
The fact that it has been closed without any comment or commit tells me that it hasn't.

**Comment by lumien231** [comment]
http://minecraft.curseforge.com/projects/perfect-spawn/files/2212916

**Comment by 4rz0** [comment]
Serves me right for only going after github commits.
Thanks for your response, I'll give it a try!
