### ISSUE TITLE
Beds explode in 1.1 for 1.7.10 in all dims but spawn dim.

### ISSUE THREAD

**Issue by ProsperCraft** [lumien231/Perfect-Spawn#11]
The only bed we can use is the decocraft bed.  Carpenters beds explode as well as vanilla and LOTR beds.

This happens with forceBed true or false.

Please add an option to disable exploding beds.

**Comment by Kiyaku** [comment]
Second this, kinda caught me by surprised when i tried to sleep in the overworld hehe. An option or something would be great!
