### ISSUE TITLE
Crash on first load with different Dimension

### ISSUE THREAD

**Issue by JasonMcRay** [lumien231/Perfect-Spawn#12]
I have Galacticraft installed and I used your mod to change the spawn to dimesnion -28 (which is moon).

Problem is, that on the first start of the world, the minecraft crashes with: http://paste.ee/p/jr9sm
When I restart minecraft and load the world again. Everything is fine. I am at the specified coords in specified dimension.

Only the initial start is annoying.

Happens in 1.7.10 - v1.1 of Perfect Spawn

**Comment by lumien231** [comment]
Can you reproduce this with only Galacticraft and Perfect Spawn?

**Comment by JasonMcRay** [comment]
Sorry I should have said that I am using my custom modpack (InfiTech 2) Nope. Works fine with just couple of mods. Also I tried to add some more mods, that I have and that affects Galacticraft dimensions in case they were the cause. But no. It loads perfectly. The issue comes with bigger modpack (I was testing it on Infitech 2 modpack)

It seems like the problem might be with bigger modpacks, where there is a lot of stuff to load, so the dimensions are not loaded fast enough for Perfect Spawn.

**Comment by jredfox** [comment]
Ok have you tried setting exact spawn to false? It helped me not crash in the tropics
