### ISSUE TITLE
Class transformer crash with Galacticraft's WorldProviderSpace

### ISSUE THREAD

**Issue by radfast** [lumien231/Perfect-Spawn#17]
Hey @lumien231 

https://github.com/micdoodle8/Galacticraft/issues/2824

The NoClassDefFound error seen there is most likely in fact an Exception thrown inside a ClassTransformer on the attempt to load the class (I hate how Java doesn't report the full cause of the issue)

I think it's likely that the cause of the crash is the attempt to transform our [overridden methods](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/api/prefab/world/gen/WorldProviderSpace.java#L296-L340) in ```WorldProvider```

A simple solution could be to blacklist any instance of ```WorldProviderSpace``` from your class transformer?

Note that Galacticraft and its add-ons will add many new ```WorldProvider``` classes which are sub-classes of ```WorldProviderSpace``` - basically each planet has its own WorldProvider class, and we currently have 4 planets + space stations, and Galacticraft add-on mods written by other authors add a whole lot more.

**Comment by MyNameBeMrRandom** [comment]
Can this be seen by someone that can fix it maybe, this mod could be useful for a lot of modpacks

**Comment by lumien231** [comment]
Currently rewriting it which should also fix this, should be ready in a week or so.
