### ISSUE TITLE
Suggestion: Spawn command

### ISSUE THREAD

**Issue by ChatFawkes** [lumien231/Perfect-Spawn#3]
Would it be possible to add a spawn command that could take you back to the spawn when used? Also somehow make it possible for non-opped players to use the command (maybe through a config option)? This is a suggestion for the 1.7.10 version of the mod.

**Comment by ChatFawkes** [comment]
Hey I saw that this is available for the 1.8 version of the mod. Any chance you could port that to 1.7.10? If not that's fine.

**Comment by lumien231** [comment]
No i can't :/, i've accidentally deleted the 1.7.10 source code so i would have to port the 1.8 version back which i really don't wanna do.
