### ISSUE TITLE
suggestion: random spawn location starting at spawn point specified, and smart spawning

### ISSUE THREAD

**Issue by Prophious** [lumien231/Perfect-Spawn#4]
even when i have the "exactSpawn": false it still will spawn me exactly there, i'm trying to spawn in the nether.... the only thing that changes is the y cords.... but i would like it to look for a good place to spawn, perhaps looking for non-liquid blocks and maybe 5-10 blocks away if possible..... and some sort of randomness with spawning, like setting a zone to randomly spawn in to like x: -100 to x: 100, z: -100 to z: 100, y:54 to y:90.... tbh i dont know if another mod works like that... and not asking if you know.....

info: for version minecraft 1.7.10, running latest forge, other mods included

**Comment by lumien231** [comment]
exactSpawn:true just removes the odd vanilla mechanic that tends to spawn you on top of buildings when your spawn is not under the sky.

I can't really specify conditions for selecting a random spawn point since i don't know where the users puts it. Random Spawn & Spawn in a selected area will be added next version.

**Comment by Prophious** [comment]
ok cool, but would the 1.7.10 version get updated with that, or only 1.8+?

**Comment by lumien231** [comment]
I will do the 1.8 version first and if its easy to backport i'll do it.

**Comment by Prophious** [comment]
awesome, ya see there are still alot of mods on 1.7.10 and this perfect spawn seems to give me exactly what i need, but i guess you can see where i'm going with this, i would love to use this mod and all the randomness of a specified spawn zone in my modpack

**Comment by Prophious** [comment]
just curious, any luck with update with feature?

i'd love to help, but coding is not my strongest hobby, perhaps its one of the weakest atm

**Comment by Prophious** [comment]
not to bug or anything, but any luck with the mod for 1.7.10, i really haven't looked at the curse webpage for this mod
