### ISSUE TITLE
1.7.10 World Corrupting

### ISSUE THREAD

**Issue by BLSK** [lumien231/Perfect-Spawn#7]
PerfectSpawn 1.1
Forge 1403

I have Mystcraft in my Modpack and was planning to use perfect spawn to adjust the starter spawn to world -500... started it up and all seemed fine then I tried to log into my server and client crashed due to mystcraft and I would assume your mod interacting with it?  The server map became corrupted.

The Server Console info I have is classified as too big for pastebin... by like 9x... so trying to filter out what seems to be the problem.  It's 60k lines to try and find anything so not sure how well it will play out there...  90% of the lines seem to say something about Perfect Spawn.

There have been a few cases where 'Forge' version has been an issue...  I have stumbled on a few in the last few months.

If I can I will look though it but I thought in the least I would mention this and give it a day or 2 for maybe its something simple like the forge thing.  I can't really go lower though.

EDIT-------------------------------------------
Setting like world 0 and what not seem to work right but Mystcraft worlds are corrupting

**Comment by lumien231** [comment]
It's too big if you just run the server and login? o_O.

**Comment by BLSK** [comment]
Well I tried out, only myst and perfect together .... no issues....

Granted I can't be sure whats happening now... If it turned out it was Perfect spawn I would come back and reopen...other than that....Closing...
Gotta love Mysteries...
