### ISSUE TITLE
Excessive DEBUG log messages.

### ISSUE THREAD

**Issue by Blargerist** [lumien231/Perfect-Spawn#9]
https://github.com/lumien231/Perfect-Spawn/blob/master/src/main/java/lumien/perfectspawn/Transformer/PSClassTransformer.java#L41

While looking at a log for a problem related to one of my mods, I found myself having trouble finding information due to at least 50% of the log file consisting of your transformer logs.

I know 10,000+ log messages may seem reasonable. And I know it's not much of a problem since its in debug and therefore only written to the log files. Surely this much information cannot be useful though? Please, can you only print classes you are actually transforming, and not every single class that passes through your transformer method? Unless you need that much information for something?

**Comment by lumien231** [comment]
Yeah, i fixed this in the 1.8 version. Might make another update for the 1.7.10 one.
